name: flutter_furniture_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  # cloud_firestore: ^0.16.0+1
  flutter_bloc: ^7.1.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/sofas-category-image.png
    - assets/images/sofa-bett.png
    - assets/images/sofa-sven.png
    - assets/images/sofa-ron.png
    - assets/images/sofa-elisa.png

 
  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf