name: flutter_furniture_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/sofas-category-image.png
    - assets/images/sofa-bett.png
    - assets/images/sofa-sven.png
    - assets/images/sofa-ron.png
    - assets/images/sofa-elisa.png
    - assets/images/sofa-osvald-large.png

 
  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf